name: CI Pipeline

on:
 push:
  branches: [ main ]

jobs:
 build:
  run-on: ubuntu-latest

 steps:
  name: Checkout code
  uses: actions/checkout@v5

  name: Set up Node.js
  uses: actions/setup-node@v3
  with:
   node-version: 16

  name: Install dependecies
  uses: npm install 

  name: Run tests
  uses: npm test